development:
  email_domain: lists.yourdomain.com
  email_target_url: http://lists.yourdomain.com/emails
  copyright: '&copy;2009 Your Company'
  
test:
  email_domain: lists.yourdomain.com
  email_target_url: http://lists.yourdomain.com/emails
  copyright: '&copy;2009 Your Company'

production:
  email_domain: lists.yourdomain.com
  email_target_url: http://lists.yourdomain.com/emails
  copyright: '&copy;2009 Your Company'
