development:
  email_domain: lists.yourdomain.com
  email_target_url: http://lists.yourdomain.com/emails
  
test:
  email_domain: lists.yourdomain.com
  email_target_url: http://lists.yourdomain.com/emails

production:
  email_domain: lists.yourdomain.com
  email_target_url: http://lists.yourdomain.com/emails
